### PR TITLE
Run tests in GitHub Actions

### PR DESCRIPTION
**Pull request by nikosavola**
This PR adds testing in GitHub Actions CI.

### CODE REVIEW

**Comment by PhilippAumann** [comment]
Looks very helpful, thank you!

**Comment by PhilippAumann** [comment]
Interestingly, GitHub Actions throws an error for the test, while the test did pass locally on my machine. I have been using the latest `scipy` version (v1.6.2) which is provided within the standard `conda` distribution. After I installed the most recent `scipy` version on `PyPI` (v.1.7.1), I was able to reproduce the error also locally. It seems that the calculation of the eigenstates somehow changed - at least I now get different numerical values. I will have a look at it - guess it will have something to do with ordering or accuracy.

**Comment by nikosavola** [comment]
> Interestingly, GitHub Actions throws an error for the test, while the test did pass locally on my machine. I have been using the latest `scipy` version (v1.6.2) which is provided within the standard `conda` distribution. After I installed the most recent `scipy` version on `PyPI` (v.1.7.1), I was able to reproduce the error also locally. It seems that the calculation of the eigenstates somehow changed - at least I now get different numerical values. I will have a look at it - guess it will have something to do with ordering or accuracy.

At least the CI now does its job and problems are found 😅

**Comment by PhilippAumann** [comment]
The reason for the test failing with the new `scipy` version were two-fold: First, the sign of some eigenstates was different, compared to before - however this has no physical meaning. Second, there were some - I guess solely numerical - deviations for higher eigenstates.
I have replaced the former naive comparison of the eigenstates by a comparison of the absolute square of the eigenstates and check only the first 10 eigenstates, as higher eigenstates shouldn't play a big role anyway.

**Pull request merged**
